# Generated by Django 5.2.5 on 2025-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('preset_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('creator_id', models.BigIntegerField()),
                ('creator_name', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
                ('flags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('arguments', models.TextField(blank=True, null=True)),
                ('official', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('gen_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'presets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bot_admin', models.IntegerField()),
                ('git_user', models.IntegerField()),
                ('race_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedPreset',
            fields=[
                ('preset_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('featured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
