# Generated by Django 5.2.5 on 2025-08-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedLog",
            fields=[
                ("creator_id", models.BigIntegerField()),
                ("creator_name", models.TextField()),
                ("seed_type", models.TextField()),
                ("share_url", models.TextField(blank=True, null=True)),
                ("timestamp", models.TextField(primary_key=True, serialize=False)),
                ("server_name", models.TextField(blank=True, null=True)),
                ("server_id", models.BigIntegerField(blank=True, null=True)),
                ("channel_name", models.TextField(blank=True, null=True)),
                ("channel_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "seedlist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="presets.preset"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "preset")},
            },
        ),
    ]
