# Generated by Django 4.2.23 on 2025-08-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedLog',
            fields=[
                ('creator_id', models.BigIntegerField()),
                ('creator_name', models.TextField()),
                ('seed_type', models.TextField()),
                ('share_url', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(primary_key=True, serialize=False)),
                ('server_name', models.TextField(blank=True, null=True)),
                ('server_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seedlist',
                'managed': False,
            },
        ),
    ]
